# Site settings
title: "The Modern 18-Factor App"
description: "An evolution of the twelve-factor methodology for modern cloud-native applications"
baseurl: "/12-factor-app-website"
url: "https://pierrebrunelle.github.io"
author: "Pierre Brunelle"

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Disable Sass processing completely
sass:
  sass_dir: null
  style: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Include Font Awesome
head_scripts:
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"

# Collections
collections:
  factors:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "factors"
    values:
      layout: "factor"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "Factors 1-12"
    url: "/#factors"
  - name: "New Factors 13-18"
    url: "/#factors"

# Social links
social:
  github: "pierrebrunelle/12-factor-app-website"

# SEO
seo:
  type: "WebSite"
  name: "The Modern 18-Factor App"
  links:
    - "https://github.com/pierrebrunelle/12-factor-app-website"